COMBO_ENABLE      = yes
MOUSEKEY_ENABLE   = yes
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE  = no
UNICODE_COMMON    = yes
UNICODE_ENABLE    = no
UNICODEMAP_ENABLE = yes
CAPS_WORD_ENABLE  = yes
USER_NUM_WORD_ENABLE = yes
CONSOLE_ENABLE    = no

